### ISSUE TITLE
optional return parameters in python wrapper

### ISSUE THREAD

**Issue by MMesch** [MarkWieczorek/SHTOOLS#1]
f2py always calls Fortran functions with the full argument list, filling optional parameters with default values. The "present" statement in Fortran therefore always returns True and can not be used. 

In case of optional input parameters, we can check for default parameters that indicate their presence in the PythonWrapper.f95 subroutine but this doesn't work for optional return parameters. 

An example is the PreCompute subroutine which so far can only return zeros and weights but not the array "plx" . We might have to create two subroutines to handle each return case separately.

**Comment by MarkWieczorek** [comment]
Routines with **intent(out), optional** include
- PreCompute
- SHRead
- MakeMagGridDH
- SHExpandLSQ
- SHReturnTapersM
- SHAdmitCorr
- SHLocalizedAdmitCorr
- SHMTVarOpt0
- SHReadJPL
- SHRead2
- MakeCircleCoord
- SHMTVarOpt
- MakeGravGridDH
- MakeEllipseCoord

**Comment by MMesch** [comment]
The SHRead routines provide many optional arguments. It might be easier to rewrite them directly in python.
